environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
  - TARGET: i686-pc-windows-gnu
  - TARGET: x86_64-pc-windows-gnu

install:
  - net user %USERNAME% Testpw123!+
  - set TEST_PW=Testpw123!+
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V
  - mkdir c:\test
  - ps: |
      "hello world" | Out-File -encoding ascii c:\test\index.html -NoNewline
      Import-Module WebAdministration
      New-Item iis:\Sites\TestSite -bindings @{protocol="http";bindingInformation=":80:"} -physicalPath c:\test
      Set-WebConfigurationProperty -filter /system.webServer/security/authentication/windowsAuthentication -name enabled -value true -PSPath IIS:\ -Location TestSite
      Set-WebConfigurationProperty -filter /system.webServer/security/authentication/anonymousAuthentication -name enabled -value false -PSPath IIS:\ -Location TestSite
      Start-Service W3SVC
      Stop-Website "Default Web Site"
      Start-Website TestSite

build: false

test_script:
  - cargo test --target %TARGET% --all
