jobs:
- job: ${{ parameters.name }}
  displayName: Min supported Rust version
  pool:
    # On Windows we have all features available, so makes sense for min rust version
    vmImage: windows-2019
  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: ${{ parameters.rust_version }}

  - script: cargo check --all
    displayName: cargo check --all
